### ISSUE TITLE
No Docker

### ISSUE THREAD

**Issue by MyCodeRocks** [lephisto/pfsense-analytics#13]
Hi there,

Might be a really dumb question but are you considering creating a non Docker version of this. I already have a Graylog & Elastic instance running on bare metal and would like to use that.

**Comment by e-d-i-t** [comment]
I'm rebuilding this whole thing manually on a single Ubuntu using sniplets of this docker config and https://marketplace.graylog.org/addons/e2f1e6cf-e4ac-4f5b-95ae-e8f377d43187.
Now have to install grafana, but I am still looking how Influx is put in between them. Although it is not mentioned in the other project.
