### ISSUE TITLE
Setup error on docker_elasticsearch_1; docker_mongodb_1; elasticsearch

### ISSUE THREAD

**Issue by swizzlest** [lephisto/pfsense-analytics#16]
Hello, I have reached this point where I get an error and the installation fails.  Any ideas on what I can check?  Thank you!

ERROR: for docker_elasticsearch_1  Cannot start service elasticsearch: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \\"process_linux.go:359: setting rlimits for ready process caused \\\\\\"error setting rlimit type 8: operation not permitted\\\\\\"\\"": unknown'

ERROR: for docker_mongodb_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for elasticsearch  Cannot start service elasticsearch: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \\"process_linux.go:359: setting rlimits for ready process caused \\\\\\"error setting rlimit type 8: operation not permitted\\\\\\"\\"": unknown'

ERROR: for mongodb  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

**Comment by swizzlest** [comment]
I have attempted again today while changing the hostname to the name of the DockerLXC running on my proxmos, and got a *little* farther.  Please see new error:

ERROR: for docker_elasticsearch_1  Cannot start service elasticsearch: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \\"process_linux.go:359: setting rlimits for ready process caused \\\\\\"error setting rlimit type 8: operation not permitted\\\\\\"\\"": unknown'

ERROR: for elasticsearch  Cannot start service elasticsearch: b'OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \\"process_linux.go:359: setting rlimits for ready process caused \\\\\\"error setting rlimit type 8: operation not permitted\\\\\\"\\"": unknown'
ERROR: Encountered errors while bringing up the project.

**Comment by lephisto** [comment]
Dunno never tested with LXC. I don't like the Idea of running a Container inside a Container. Go with straight docker.
