### ISSUE TITLE
Docker graylog server is up but accesing port 9000 just gives me a white screen

### ISSUE THREAD

**Issue by thanhtranntkh** [lephisto/pfsense-analytics#18]
Docker graylog server is up but accesing port 9000 just gives me a white screen
![111](https://user-images.githubusercontent.com/20314470/76217534-2caca980-6245-11ea-9ca6-5296a370bdbc.png)

**Comment by prasket** [comment]
appears to be related to https://github.com/lephisto/pfsense-analytics/issues/17

**Comment by skrmn** [comment]
I have the same issue. Grafana, Cerebro, opens fine. 
White screen on Graylog itself.
Ubuntu server 18.04.4

Can it be fixed?

**Comment by skrmn** [comment]
Fixed by passing GRAYLOG_HTTP_EXTERNAL_URI with servers external address.

**Comment by thanhtranntkh** [comment]
thank you. I do not use docker
I install on ubuntu and took advantage of your configuration

**Comment by amchawawa** [comment]
Worked for me by doing the following:

By edit the ./Docker/graylog.env

GRAYLOG_HTTP_EXTERNAL_URI (eg: http://your server IP:9000)

The to restart the Graylog server  I just rerun this command:

cd ./Docker
sudo docker-compose up

**Comment by mrandrewdh** [comment]
Should cerebro be exposing :9000 as well as graylog?
In the docker-compose file both services are running on 9000 using the same host ip

**Comment by amchawawa** [comment]
Hi 

No Cerebro must be on port:9001 it won't work if both are on the same port

**Comment by mrandrewdh** [comment]
> Hi
> 
> No Cerebro must be on port:9001 it won't work if both are on the same port

Thats what I was thinking - but strangely they do (I can access both web interfaces - cerebro on 9001) even though the compose file has both services configured to 9000...is this a bug or am i missing something
