### ISSUE TITLE
Running pfsense-analytics on Synology Docker

### ISSUE THREAD

**Issue by promo76** [lephisto/pfsense-analytics#19]
Hello,

Is there a way to run this solution on Synology Docker?

Thank you,

Mike

**Comment by wifiuk** [comment]
would be good if there was an image we can pull from somewhere like docker-hub with all the dependencies needed to be included... It's me being lazy I guess, as I just don't have to have to set up all the separate containers and link them together lol

**Comment by lephisto** [comment]
I have no idea about synology. This Stack should run on normal Linuxes with Docker + compose.
