### ISSUE TITLE
Step 5 (Cerebro)

### ISSUE THREAD

**Issue by rwarrick85** [lephisto/pfsense-analytics#2]
Getting error when entering the 'Node Address'

**Comment by lephisto** [comment]
What error do you get. What Address do you enter.

**Comment by rwarrick85** [comment]
I entered http://localhost:9001 from the host and used the IP address from another machine on the same network - same error.

This is the message: 
  Error connecting to [http:192.168.1.156:9001]


When I click on the error:

"\n<!DOCTYPE html>\n<html lang=\"en\">\n    <head>\n        <title>Error</title>\n        \n<style  type=\"text/css\">\n            html, body, pre {\n                margin: 0;\n                padding: 0;\n                font-family: Monaco, 'Lucida Console', monospace;\n                background: #ECECEC;\n            }\n            h1 {\n                margin: 0;\n                background: #A31012;\n                padding: 20px 45px;\n                color: #fff;\n                text-shadow: 1px 1px 1px rgba(0,0,0,.3);\n                border-bottom: 1px solid #690000;\n                font-size: 28px;\n            }\n            p#detail {\n                margin: 0;\n                padding: 15px 45px;\n                background: #F5A0A0;\n                border-top: 4px solid #D36D6D;\n                color: #730000;\n                text-shadow: 1px 1px 1px rgba(255,255,255,.3);\n                font-size: 14px;\n                border-bottom: 1px solid #BA7A7A;\n            }\n        </style>\n    </head>\n    <body>\n        <h1>Oops, an error occurred</h1>\n\n        <p id=\"detail\">\n            This exception has been logged with id <strong>7dpok05ml</strong>.\n        </p>\n\n    </body>\n</html>"

**Comment by lephisto** [comment]
So the Cerebro login page doesn't load, or you can't connect from Cerebro to your ES?

**Comment by rwarrick85** [comment]
It loads, it will not accept the Node Address. Keeps giving me the error.

**Comment by lephisto** [comment]
You gotta put in the name within the Dockerstack, that's http://elasticsearch:9200.

```
none - provide with ES API: http://elasticsearch:9200
```

check docs..
