### ISSUE TITLE
No Data Appearing on the Maps in Grafana

### ISSUE THREAD

**Issue by philam776** [lephisto/pfsense-analytics#20]
Everything else is working fine in Grafana and Graylog. My only issue is that there is no map data being shown in either the Firewall Logs or DPI dashboards. I used #15 to help me refer to my licence key within getGeo.sh in order to build Graylog in the first place, but even though it was built, there is still nothing being shown on either maps in Grafana. Anyone else having this issue? 

Thanks for the help 
![grafana](https://user-images.githubusercontent.com/64231645/80517239-c1cd4400-8952-11ea-95c1-d57e75748b0d.jpg)

**Comment by jackdanpr** [comment]
I hear you man... For some reason is not working. I think is something with geo_location mapping someplace on graylog, kibana or who knows where...
I hope someone jump up and have a resolution.

**Comment by jtbisaha** [comment]
GEOIP was completely missing from the Graylog image for me.  I had to manually set it up with [this guide](https://www.graylog.org/post/implementing-geolocation-with-graylog-pipelines).  

Use this for the rule instead of Graylog's version:
```
rule "GeoIP lookup: src_ip"
when
   has_field("src_ip")
then
   let geo = lookup("geoip", to_string($message.src_ip));
   set_field("src_location", geo["coordinates"]);
   set_field("src_ip_geo_country", geo["country"].iso_code);
   set_field("src_ip_geo_city", geo["city"].names.en);
end
```

**Comment by ShermanTenor** [comment]
pfSense NTOPNG v0.8.13_5 includes a spot to define your maxmind license key:

Diagnostics> ntopng Settings> GeoLite2 DB License Key

I was getting location info into the firewall dashboard using https://github.com/lephisto/pfsense-analytics/issues/15, like the OP, but NTOPNG didn't have a key defined.  Now that I have that in place, data is flowing to the map areas nicely.

**Comment by philam776** [comment]
@ShermanTenor I entered my GeoLite2 License Key into the NTOPNG spot as well as the my getGeo.sh file. My DPI dashboard maps are now WORKING (so thank you for that advice). But, my firewall logs are still not working, even though the key that I typed into NTOPNG is identical to the one I typed into my getGeo.sh file.

Would you mind posting exactly what you have in your getGeo.sh file? (minus the license key of course). I might have some error within there possibly that's not allowing it to work?

Here is my current getGeo.sh file:

curl --output /etc/graylog/server/mm.tar.gz 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=MYKEYISHERE&suffix=tar.gz'
tar zxvf /etc/graylog/server/mm.tar.gz -C /etc/graylog/server/ --strip-components=1

Again, thanks for all the help so far. Very new to all of this.

**Comment by jackdanpr** [comment]
Try this;
curl --output /etc/graylog/server/mm.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=MYKEYISHERE&suffix=tar.gz"
tar zxvf /etc/graylog/server/mm.tar.gz -C /etc/graylog/server/ --strip-components=1

Please note that you should put your https://download.. link with double quotes (").
That worked for me...

Make sure this folder is created "/etc/graylog/server/"
One issue I had was with "tar zxvf..." I just remove the "z" (tar xvf)

I had a bunch of other issues to get working, I will post it here later today. Just in case someone need it...

Thanks,

**Comment by ShermanTenor** [comment]
> @ShermanTenor I entered my GeoLite2 License Key into the NTOPNG spot as well as the my getGeo.sh file. My DPI dashboard maps are now WORKING (so thank you for that advice). But, my firewall logs are still not working, even though the key that I typed into NTOPNG is identical to the one I typed into my getGeo.sh file.
> 
> Would you mind posting exactly what you have in your getGeo.sh file? (minus the license key of course). I might have some error within there possibly that's not allowing it to work?
> 
> Here is my current getGeo.sh file:
> 
> curl --output /etc/graylog/server/mm.tar.gz 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=MYKEYISHERE&suffix=tar.gz'
> tar zxvf /etc/graylog/server/mm.tar.gz -C /etc/graylog/server/ --strip-components=1
> 
> Again, thanks for all the help so far. Very new to all of this.

Sure - here is my getGeo.sh file:

curl --output /etc/graylog/server/mm.tar.gz 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=xxxxxxxxxxxxxxxx&suffix=tar.gz'
tar zxvf /etc/graylog/server/mm.tar.gz -C /etc/graylog/server/ --strip-components=1

**Comment by jackdanpr** [comment]
Not receiving log from pfsense is another thing...
Let me tell you what I found;
Firewall dashboard grafana; 
Go to the Time Picker and choose 2 days or more, I don't know why, but data from 1 hour doesn't show.
Also, if you go to one of the panels and  enter "edit", remove the query string and enter just an asterisk (*), you should see data coming (don't ask, I don't know why...)

Make sure you have configure pfsense to send logs to graylog (Status, System Logs, Settings>>Remote Logging Options >> remote log server "graylog_ip:5442" >> check "firewall events" and "save".

If you want to edit grafana dashboards, you need to edit the .json files. Make copies of those files (ndpi.json & firewall.json) then edit accordingly. (~/pfsense-analytics/Docker/grafana/provisioning/dashboards/)

If you don't mind, how is your hardware doing? I'm running VM Ubuntu and it's almost 3GB of ram all the time...

![Capture](https://user-images.githubusercontent.com/24983773/80852626-12190000-8bf8-11ea-8f2d-4f7f30591e7c.JPG)

Thanks for sharing...

**Comment by jackdanpr** [comment]
![Capture2](https://user-images.githubusercontent.com/24983773/80852864-07f80100-8bfa-11ea-9d2e-90c854e01c60.JPG)

**Comment by philam776** [comment]
@jackdanpr Did you configure anything extra in your Graylog settings? Like what @jtbisaha did using the Graylog pipelines? In the above post you made with using the asterisk to bring up that data... did you have to configure the src_ip_city_name and src_ip_country_code to be located there in Grafana or was it there automatically? 

My only problem still stands as I am receiving no geolocation data for my firewall logs in Grafana. I have tried using the pipelines in Graylog, but that hasn't worked either.

**Comment by jackdanpr** [comment]
To be honest, I have made so many tweaks that don't remember much, but I would try to help anyway...
One thing, make sure you have your times correct on "Systems >> Overview"...

**Comment by DANgerous25** [comment]
> Not receiving log from pfsense is another thing...
> Let me tell you what I found;
> Firewall dashboard grafana;
> Go to the Time Picker and choose 2 days or more, I don't know why, but data from 1 hour doesn't show.
> Also, if you go to one of the panels and enter "edit", remove the query string and enter just an asterisk (*), you should see data coming (don't ask, I don't know why...)
> 
> Make sure you have configure pfsense to send logs to graylog (Status, System Logs, Settings>>Remote Logging Options >> remote log server "graylog_ip:5442" >> check "firewall events" and "save".
> 
> If you want to edit grafana dashboards, you need to edit the .json files. Make copies of those files (ndpi.json & firewall.json) then edit accordingly. (~/pfsense-analytics/Docker/grafana/provisioning/dashboards/)
> 
> If you don't mind, how is your hardware doing? I'm running VM Ubuntu and it's almost 3GB of ram all the time...
> 
> ![Capture](https://user-images.githubusercontent.com/24983773/80852626-12190000-8bf8-11ea-8f2d-4f7f30591e7c.JPG)
> 
> Thanks for sharing...

I'm also having the problem with no points on the map for the firewall logs. Everything else is working, including the NPI dashboard where I am getting points on the map. 

On the other dashboard widgets for the firewall logs I can see that the country names, geo locations, etc. are all being populated. So it seems that my Maxmind stuff is working. It's just the map points that don't display. 

When I try to mirror your query settings from your screenshot @jackdanpr , I get the error message "missing geohash value". The error only disappears if I include "group by / **geo hash grid** / src location / precision [whatever]", at which point the map is still blank.

I'm using ES 6.5, Grafana 7.0.3. I can see all the data in Graylog.

I've no idea how to diagnose this as this is the first time using Grafana/ES/Graylog and JSON (it's a miracle I got this far, there were many bumps!). Any help would be appreciated.

**Comment by renanwilliam** [comment]
My problem was in getGeo.sh file. I was downloading geoLite-Country instead getLite-Cities.

Change [this](https://github.com/lephisto/pfsense-analytics/blob/1fcf407b1d9666ca107200a89761d5eb5626c97f/Docker/graylog/getGeo.sh#L1) for this:
`curl --output /etc/graylog/server/mm.tar.gz 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=MYKEYISHERE&suffix=tar.gz'`

**Comment by sod85** [comment]
Hi, did you resolve the issue?
I followed all steps in the guide and graylog receives data but grafana has no data to show.
I don´t know how to fix it....

Thanks

**Comment by lephisto** [comment]
Fixed in current Version.
