### ISSUE TITLE
Step 5/6 problem

### ISSUE THREAD

**Issue by kkrautwald** [lephisto/pfsense-analytics#24]
Hello 
When running docker-compose up:

Step 5/6 : RUN chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh
 ---> Running in 7ba489eb790e
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: geolite.maxmind.com

My server can resolve geolite.maxmind.com, because Maxmind is now a paid db. 

How to I change that?

**Comment by kkrautwald** [comment]
Never mind, I found the result, in another link.

**Comment by samcallen** [comment]
@kkrautwald how did you solve this problem? Step 5/6 : RUN chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh
---> Running in 7ba489eb790e
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (6) Could not resolve host: geolite.maxmind.com

**Comment by kkrautwald** [comment]
> @kkrautwald how did you solve this problem? 

Yes, I did with this in getGeo.sh 
curl --output /etc/graylog/server/mm.tar.gz 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=[LICENSED-KEY]&suffix=tar.gz'

That key is obtained from maxmind.com after setup of an account.....

**Comment by samcallen** [comment]
thanx
