### ISSUE TITLE
how to update and upgrade graylog installed using pfsense-analytics?

### ISSUE THREAD

**Issue by samcallen** [lephisto/pfsense-analytics#25]

**Comment by LKLAW** [comment]
Just pull the latest image?

**Comment by kkrautwald** [comment]
in folder of graylog, there is the Dockerfile - change:
FROM graylog/graylog:3.1 to FROM graylog/graylog:3.3

Remove container - and start again with docker-compose up -d

**Comment by e-d-i-t** [comment]
Tried that, next thing happens some error bewteen another docker and ID problem. I am not familiar with Docker though. But I begin to understand a little bit. Just changing to new version, delete current container does not work. There is a dependence somewhere. These kind of "servers" joining together for just a dashboard, I understand the need of Docker instantly though hahaha!

**Comment by e-d-i-t** [comment]
Found it. Needed to edit /Docker/graylog/Dockerfile to using 3.3.
