### ISSUE TITLE
Error in Cerebro

### ISSUE THREAD

**Issue by rp1783** [lephisto/pfsense-analytics#27]
Receiving this error:

`  "error": "JsResultException(errors:List((,List(JsonValidationError(List('attributes' is undefined on object: {\"name\":\"vJ9IPvf\",\"transport_address\":\"172.18.0.2:9300\",\"host\":\"172.18.0.2\",\"ip\":\"172.18.0.2\",\"version\":\"6.8.5\",\"build_flavor\":\"oss\",\"build_type\":\"docker\",\"build_hash\":\"78990e9\",\"roles\":[\"master\",\"data\",\"ingest\"],\"os\":{\"refresh_interval\":\"1s\",\"refresh_interval_in_millis\":1000,\"name\":\"Linux\",\"pretty_name\":\"CentOS Linux 7 (Core)\",\"arch\":\"amd64\",\"version\":\"4.15.0-101-generic\",\"available_processors\":4,\"allocated_processors\":4},\"jvm\":{\"pid\":1,\"version\":\"13.0.1\",\"vm_name\":\"OpenJDK 64-Bit Server VM\",\"vm_version\":\"13.0.1+9\",\"vm_vendor\":\"AdoptOpenJDK\",\"start_time\":\"2020-05-26T03:05:04.547Z\",\"start_time_in_millis\":1590462304547,\"mem\":{\"heap_init\":\"1gb\",\"heap_init_in_bytes\":1073741824,\"heap_max\":\"990.7mb\",\"heap_max_in_bytes\":1038876672,\"non_heap_init\":\"7.3mb\",\"non_heap_init_in_bytes\":7667712,\"non_heap_max\":\"0b\",\"non_heap_max_in_bytes\":0,\"direct_max\":\"0b\",\"direct_max_in_bytes\":0},\"gc_collectors\":[\"ParNew\",\"ConcurrentMarkSweep\"],\"memory_pools\":[\"CodeHeap 'non-nmethods'\",\"Metaspace\",\"CodeHeap 'profiled nmethods'\",\"Compressed Class Space\",\"Par Eden Space\",\"Par Survivor Space\",\"CodeHeap 'non-profiled nmethods'\",\"CMS Old Gen\"],\"using_compressed_ordinary_object_pointers\":\"true\",\"input_arguments\":[\"-Xms1g\",\"-Xmx1g\",\"-XX:+UseConcMarkSweepGC\",\"-XX:CMSInitiatingOccupancyFraction=75\",\"-XX:+UseCMSInitiatingOccupancyOnly\",\"-Des.networkaddress.cache.ttl=60\",\"-Des.networkaddress.cache.negative.ttl=10\",\"-XX:+AlwaysPreTouch\",\"-Xss1m\",\"-Djava.awt.headless=true\",\"-Dfile.encoding=UTF-8\",\"-Djna.nosys=true\",\"-XX:-OmitStackTraceInFastThrow\",\"-Dio.netty.noUnsafe=true\",\"-Dio.netty.noKeySetOptimization=true\",\"-Dio.netty.recycler.maxCapacityPerThread=0\",\"-Dlog4j.shutdownHookEnabled=false\",\"-Dlog4j2.disable.jmx=true\",\"-Djava.io.tmpdir=/tmp/elasticsearch-125629727188914072\",\"-XX:+HeapDumpOnOutOfMemoryError\",\"-XX:HeapDumpPath=data\",\"-XX:ErrorFile=logs/hs_err_pid%p.log\",\"-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m\",\"-Djava.locale.providers=COMPAT\",\"-XX:UseAVX=2\",\"-Des.cgroups.hierarchy.override=/\",\"-Des.path.home=/usr/share/elasticsearch\",\"-Des.path.conf=/usr/share/elasticsearch/config\",\"-Des.distribution.flavor=oss\",\"-Des.distribution.type=docker\"]}}),WrappedArray())))))"
`

**Comment by Thrilleratplay** [comment]
@rp1783  @lephisto   I just ran into this error myself.  It looks like it is an issue with the latest version of Cerebro lmenezes/cerebro#/448 
To fix this, specify the Cerebro version 0:9.0 in the [docker-compose file](https://github.com/lephisto/pfsense-analytics/blob/master/Docker/docker-compose.yml#L68)

From this:
```
    image: lmenezes/cerebro
```
 
To this:
```
    image: lmenezes/cerebro:0.9.0
```
