### ISSUE TITLE
Service 'graylog' failed to build

### ISSUE THREAD

**Issue by cilleyperson** [lephisto/pfsense-analytics#35]
I am running Ubuntu Server 64bit on a Raspberry Pi 4 with 8 GB of RAM and a 128 GB SD card. When I trying to run the docker compose process I get the following error:

`ubuntu@ubuntu:~/pfsense-analytics/Docker$ sudo docker-compose up -d
Building graylog
Step 1/6 : FROM graylog/graylog:3.1
 ---> ca38a27808e3
Step 2/6 : USER root
 ---> Using cache
 ---> 08a76a36e96d
Step 3/6 : RUN mkdir -pv /etc/graylog/server/
 ---> Running in d7d70564f82a
standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Service 'graylog' failed to build: The command '/bin/sh -c mkdir -pv /etc/graylog/server/' returned a non-zero code: 1
`

Not sure what the issue is here. Any assistance would be very much appreciated.

**Comment by theyboosting** [comment]
Yeah, same issue here...  can't figure out a way around it.

**Comment by wintrmte** [comment]
This doesn't seem to have anything to do with the original post, the error is happening as a result of the /bin/sh -c mkdir -pv command..  

If you cut and paste it, it fails: 

root@ubuntu:/home/ubuntu/pfsense-analytics/Docker# /bin/sh -c mkdir -pv /etc/graylog/server/
mkdir: missing operand
Try 'mkdir --help' for more information.

Will have to see where this is being called in the build process, should just be able to remove the /bin/sh -c which is the issue. 


> Yeah, same issue here... can't figure out a way around it.
> 
> EDIT: this works.
> 
> A better solution is to create a GeoLite account, find your LICENCE KEY under "My Licence Key" menu voice on the left and then use that key for the permalink you can obtain in the download page.
> Use the permalink in the Docker/graylog/getGet.sh file (remember to put quotes around the url) and it should work.

**Comment by theyboosting** [comment]
> This doesn't seem to have anything to do with the original post, the error is happening as a result of the /bin/sh -c mkdir -pv command..
> 
> I'm pretty sure this is because the RPI is an arm based device and not an x86 device.. Will have to dig more, but it seems like it is an architecture issue.
> 
> > Yeah, same issue here... can't figure out a way around it.
> > EDIT: this works.
> > A better solution is to create a GeoLite account, find your LICENCE KEY under "My Licence Key" menu voice on the left and then use that key for the permalink you can obtain in the download page.
> > Use the permalink in the Docker/graylog/getGet.sh file (remember to put quotes around the url) and it should work.

Actually someone else commented what I quoted in the thread and it worked, till I ran into other issues and had to make edits in the getGet.sh file to make it actually work... I wasn't running it on arm at all, I was running it on ubuntu 20.04 server amd64 ESXi 7.0

**Comment by abol4671** [comment]
I started playing around with this tonight on a RPI 4 4GB and hit this issue. Changing pfsense-analytics/Docker/graylog/Dockerfile from `FROM graylog/graylog:3.1` to `FROM tanisperez/graylog:3.2-arm64` will allow you to get passed this. Looks like cerebro and elasticsearch dont want to start but I'll tackle digging into that next.

**Comment by christiansenandi** [comment]
I have this issue on a VM inside ESXi on a 3650M4 system running Ubuntu 20.04.1 LTS:

Static hostname: grafana
         Icon name: computer-vm
           Chassis: vm
        Machine ID: d0db15f054b6424caf07fae22bf6d6b9
           Boot ID: 3cb3dcdffcf448c0ad5035b406a2b738
    Virtualization: vmware
  Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.0-54-generic
      Architecture: x86-64



Step 5/6 : RUN chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh
 ---> Running in d79fccad7831
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: geolite.maxmind.com
tar (child): /etc/graylog/server/mm.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: Service 'graylog' failed to build: The command '/bin/sh -c chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh' returned a non-zero code: 2

any help would be appreciated 👍 


Thanks!
Andi

**Comment by lephisto** [comment]
The Issue with the changed Url / License stuff is resolved in the GL4 release.
