### ISSUE TITLE
Map now showing Map

### ISSUE THREAD

**Issue by jonubuntu** [lephisto/pfsense-analytics#36]
Here is a picture of what I am talking about.. the world map is missing some squares. I can zoom in and find detail. The entire map was there last night. Anyone else having the same issue .. see pic 
![Screenshot_5](https://user-images.githubusercontent.com/68290267/87444655-4b84c900-c5b4-11ea-92a7-8f7147d88fca.png)

**Comment by jonubuntu** [comment]
Update: this only happens on my Windows machine using Google Chrome and Firefox. On my Mac everything is fine using Safari or Chome it is fine. Maybe this is java related on my windows machine

**Comment by lephisto** [comment]
It might be an issue with the tiles provider or your connection/browser. Standard Grafana Panel.
