### ISSUE TITLE
Timeseries Database

### ISSUE THREAD

**Issue by jorgejordao** [lephisto/pfsense-analytics#37]
Hello

When i try to configure on NTOP the Influxdb it appear the following error:

![imagem](https://user-images.githubusercontent.com/68556023/87958119-0cb9ac00-caa9-11ea-9b67-bcb3bac7f4e1.png)

**Comment by jorgejordao** [comment]
No one has this issue???

**Comment by MobileBoard8758** [comment]
I went thru the install of this 2 weeks ago, and did not have this issue (all of this is new to me, but instructions were clear to follow).  
Does that error message appear after toggling driver to InfluxDB and enter the InfluxDB UTL and Database name?

**Comment by jorgejordao** [comment]
![image](https://user-images.githubusercontent.com/68556023/88546768-c28a7a80-d014-11ea-951d-508e6bb022c5.png)

**Comment by jorgejordao** [comment]
The instructions are clear to follow, but the error occours every time on this step, i've reinstalled all the process 4 times

**Comment by Tad-Ski** [comment]
I have this problem too. Incompatible InfluxDB version: required "1.5.1", found "nil"

I also went into the docker  host and made sure to update the firewall to allow port 8086, but attempting access via browser returned a 404 response - page not found.

**Comment by Tad-Ski** [comment]
> No one has this issue???

I fixed this on my end.  I was specifying http://fqdn.server.name:8086, as soon as I used the IP address all worked.

**Comment by lephisto** [comment]
You can check by logging in via ssh on your pfsense and try to telnet on that host / port combination. Often it's the case, that the firewall for some reason can't resolve.

**Comment by nukedupe** [comment]
Hi,
change ```image: 'influxdb:latest'``` to ```image: 'influxdb:1.8-alpine'``` in docker-compose.yml and it will work.
Latest is 2.0 and not compatible with ntopng.
