### ISSUE TITLE
Grafana dashboard has no data after start of month

### ISSUE THREAD

**Issue by andrewwong2000** [lephisto/pfsense-analytics#39]
Hi, 

Thanks for setting this up. It's been working great in July but after 1 August, the logfile rotation has kicked in but the indices don't seem to be working correctly - so the dashboard has no new updates.

Where might I need to look to check that the indexing/search is updating correctly at month end ?

I am still getting pfSense messages in Graylog, and indices are still running.

pfsense-logs 2 indices, 55,209,052 documents, 33.9GiB default

Rotation Strategy: Index Time
Rotation Period : P1M
Index Retention Configuration - Delete Index (after Max number of indices = 12)

**Comment by lephisto** [comment]
Index full? This could explain it. Elasticsearch stops writing when only a few % disk space is left. Check with Cerebro. there you can delete old stuff, just never delete the deflector.
