### ISSUE TITLE
Firewall Dashboard works fine but DPI dashboard shows no data

### ISSUE THREAD

**Issue by alexcavazos67** [lephisto/pfsense-analytics#42]
I had to reinstall pfsense-analytics since I screwed up some backups. It was working fine until then. Now after reinstalling, the Firewall dashboard looks fine:
![image](https://user-images.githubusercontent.com/5564545/93019601-9f3e7d80-f60a-11ea-83f9-9a5d7899cb7a.png)

but the DPI dashboard is empty (the panels are all there, they just don't have any data)
![image](https://user-images.githubusercontent.com/5564545/93019681-1f64e300-f60b-11ea-96a0-a0641634f3cc.png)

So I wanted to know, in order to troubleshoot, how can verify logs are being stored in Graylog?

**Comment by lephisto** [comment]
Then InfluxDB streaming doesn't work. Double check ntop for errors on influx streaming.
