### ISSUE TITLE
*Feature Request* Client Specific DPI

### ISSUE THREAD

**Issue by bigjohns97** [lephisto/pfsense-analytics#47]
Has anyone been able to get the NDPI dashboard to be able to show specific types of traffic per host?

I am a grafana noob and don't have the skills to make this happen but would like to be able to select a specific client ip address and then have the NDPI interface show just the traffic for that client.

**Comment by lephisto** [comment]
You can easily expand the Dashboard for NDPI. What I provide is not meant to provide the full potential that the Timeseries Export Provides.

Look into the measurement host:ndpi_categories

![image](https://user-images.githubusercontent.com/9072410/108641593-4bc93900-74a0-11eb-80b5-93c7fbca5121.png)

From there you can extract which host has generated which type of traffic easily.

**Comment by bigjohns97** [comment]
I am trying to find the host:ndpi_categories (do I need to enable something in ntopng to get this table?), I do have a variable defined that should be able to be implemented into some of the panels where it makes sense.

![image](https://user-images.githubusercontent.com/5262891/108643204-2243e980-746f-11eb-8b5b-019c7eaeb828.png)

**Comment by bigjohns97** [comment]
LOL nevermind I see now, I just need to add the where host = $variable to all of the panels.*CLICK*

this is awsome!

**Comment by bigjohns97** [comment]
Well I spoke too soon, this only works for the top panel, I can't seem to either create another AND on the ones where protocol is the selection, I am going to have to keep working on it for other panels but the top one works very easy with this edit.

![image](https://user-images.githubusercontent.com/5262891/108643561-ae0a4580-7470-11eb-9713-0bdb67d11d13.png)

**Comment by bigjohns97** [comment]
I finally got this working, thanks to @lephisto for pointing me in the right direction.

I had to enable both categories and protocols on ntopng and then I was able to add a where clause pointing to a host variable to the panels I wanted to be able to filter and enable the all as default and voila!
