### ISSUE TITLE
DPI Dashboard showing MAC instead of IP and IPv4 traffic is interpreted as IPv6 traffic

### ISSUE THREAD

**Issue by mamema** [lephisto/pfsense-analytics#48]
See screenshots

I've only have IPv4
![image](https://user-images.githubusercontent.com/18702616/106352722-b219cc00-62e5-11eb-8670-42c0e505a2c9.png)

![image](https://user-images.githubusercontent.com/18702616/106352729-bcd46100-62e5-11eb-9f5a-3ee2eb7670fe.png)

**Comment by lephisto** [comment]
Make sure you are using the latest Version of pfSense and ntop.
