### ISSUE TITLE
empty Stream in Graylog and empty Dashboard in Grafana

### ISSUE THREAD

**Issue by ShaperS4** [lephisto/pfsense-analytics#49]
Thank you very much to setting this how to up and also thank you for providing your step by step guide.

I followed your guide exactly and was able to set everything up without any error messages or other hicups. 
Sadly, how ever I can not see any data in the pfsense stream on graylog and there for i also have no data in the Grafana Dashboard.

doese anybody have any idea what the reason could be that the graylog server get no data in the stream?
I'm not very Linux experienced and there for a little lost in how to find the error my self.

thanks to every one who could help here.

Best Regards

**Comment by lephisto** [comment]
I would follow it from the source to the destination: Do you see messages on the INput of Graylog? How about the Stream processor? There are counters that tell you about this.

Have quickly watched my Video tutorial?

https://www.youtube.com/watch?v=uOfPzueH6MA&feature=youtu.be

**Comment by ShaperS4** [comment]
Thank you for your reply!

I will check again, but in Graylog i can see some messages but I habe to
check the counters again for more details.

I will also re-watch your video hopefully I can find the hic up...

If I get more details, i will update the post.

Best regards
Thomas

Bastian <notifications@github.com> schrieb am Mi., 10. Feb. 2021, 21:09:
