### ISSUE TITLE
Content Pack import fails

### ISSUE THREAD

**Issue by MatthewJSalerno** [lephisto/pfsense-analytics#5]
org.graylog2.contentpacks.exceptions.FailedConstraintsException: Failed constraints: [PluginVersionConstraint{type=plugin-version, pluginId=org.graylog.plugins.threatintel.ThreatIntelPlugin, version=>=3.1.3}, PluginVersionConstraint{type=plugin-version, pluginId=org.graylog.plugins.threatintel.ThreatIntelPlugin, version=>=3.1.2}]

For some reason, I do not see the ThreatIntelPlugin listed in the config.  Since it's not enabled and is a dependency of the content pack, the install of the content pack fails.

I'm looking through the Graylog docs to see if I missed anything.

**Comment by MatthewJSalerno** [comment]
Upgrading to graylog/graylog:3.1.3 fixes the issue.  It looks like graylog packaged the wrong version of the jar with the 3.1 container.

**Comment by MatthewJSalerno** [comment]
This is resolved in:

MatthewJSalerno:patch-1

**Comment by lephisto** [comment]
You might want to get the latest master. In your fork (which i suspect you've been testing) was a mistake, that prevented the default plugins to run. I blame this for it:

https://github.com/MatthewJSalerno/pfsense-analytics/blob/214b26304b85b7304bc8880c851db3c229658bf3/Docker/graylog/Dockerfile#L4

Check my corrections of your commits.

**Comment by MatthewJSalerno** [comment]
It had something to do with my version of graylog.  Based on the PluginVersionConstraint message I posted in the initial post, I just upgraded the graylog image from 3.1 to 3.1.3.  Once I restarted with the updated version, everything worked.

**Comment by MatthewJSalerno** [comment]
I created: https://github.com/lephisto/pfsense-analytics/pull/6

**Comment by lephisto** [comment]
I am pretty sure that this is not the root cause. Check https://www.youtube.com/watch?v=uOfPzueH6MA as prove :)
